# Generated by Django 4.2.1 on 2023-05-19 08:30
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations


def create_profile_for_existing_users(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserModel = get_user_model()
    UserProfileModel = apps.get_model("user_profile", "UserProfile")
    for user in UserModel.objects.using(db_alias).all():
        UserProfileModel.objects.using(db_alias).create(user_id=user.pk)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_profile_for_existing_users, reverse_code=migrations.RunPython.noop
        ),
    ]
