# Generated by Django 4.2.1 on 2023-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trektribe", "0005_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="views_count",
            field=models.BigIntegerField(
                default=0, verbose_name="Contatore visualizzazioni"
            ),
        ),
    ]
