name: Django CI

env:
  PYTHON_VERSION: '3.9'
  DB_NAME: trektribe_test
  DB_USER: test_user
  DB_PASSWORD: test_password

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pipenv'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Run Tests
      run: |
        pipenv run make style-check
        pipenv run make tests
      env:
        DB_ENGINE: django.db.backends.postgresql
        DB_NAME: ${{ env.DB_NAME }}
        DB_USER: ${{ env.DB_USER }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
